# Generated by Django 4.1.2 on 2023-04-23 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='apelido',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
