# Generated by Django 4.1.2 on 2023-04-24 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0003_contato_mostrar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contato',
            old_name='mostrar',
            new_name='publicado',
        ),
    ]
